<!-- Froala Text Editor CSS -->
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/froala_editor.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/froala_style.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/code_view.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/draggable.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/colors.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/emoticons.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/image_manager.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/image.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/line_breaker.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/table.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/char_counter.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/video.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/fullscreen.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/file.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/quick_insert.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/help.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/spell_checker.css">
  <link rel="stylesheet" href="assets/libs/froala-text-editor/css/special_characters.css">
  <link rel="stylesheet" href="https://froala-text-editor/cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">
